mysql:
  host: 127.0.0.1
  port: 53306
  dbname: api_mock
  # 数据库登录用户
  username: root
  # 数据库密码
  password: root123456
  # 数据库名字
  timeout: 10s
  maxConn: 200
  maxOpen: 200

logToFile:
  # 日志路径
  logSourcePath: D:/overall/project/api-mock/public/access.1010.log

  # collection 存储相对目录
  collectionStoreDir: public/collection
  # collection 名称前缀
  collectionNamePrefix: OKCC-Collection-
  # collection 子目录大小/批次大小
  batchSize: 1000
  # collection 子目录名称前缀
  collectionDirNamePrefix: dir_


