gin:
  host: 127.0.0.1
  port: 40020
  mode: debug

mysql:
  host: 127.0.0.1
  port: 53306
  dbname: api_mock
  # 数据库登录用户
  username: root
  # 数据库密码
  password: root123456
  # 数据库名字
  timeout: 10s
  maxConn: 200
  maxOpen: 200

logToFile:
  logSourcePath: D:/overall/project/api-mock/public/access.1010.log

  collectionStoreDir: public/collection
  collectionNamePrefix: OKCC-Collection-
  batchSize: 1000
  collectionDirNamePrefix: dir_

redis:
  host: 127.0.0.1
  port: 56378
  password:
  DB: 15

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: admin
  password: root123456
  vhost: local

grpc:
  host: 127.0.0.1
  port: 50051
